### ISSUE TITLE
arduino 读取数据到一定次数就会卡死

### ISSUE THREAD

**Issue by MEonday** [DFRobot/DFRobot_INA219#7]
我在arduino中尝试使用本项目来读取电压，发现每次读取次数到某个值时，我的stm32f103的bluepill就卡死了。
后面查看代码，程序运行到箭头所指处的ifelse 中
![image](https://github.com/DFRobot/DFRobot_INA219/assets/50793795/48e7cee8-ab54-4a2a-bde5-cb6ac327bddd)
看起来是内存泄漏的问题

目前我的解决办法是
使用Wire库自带的 void TwoWire::end(void)函数
在DFRobot_INA219.cpp  中  找到void DFRobot_INA219_IIC::readReg 函数，再在末尾中加上一句，如下图
![image](https://github.com/DFRobot/DFRobot_INA219/assets/50793795/63bfb8b3-6a4e-4f61-8f6c-1caa4f423a42)

测试读取次数26000次没有再出现过卡死的情况了。

**Comment by qsjhyy** [comment]
您好，根据您提供的代码来看，是您所使用的Wire库中存在用法差异；我们目前所兼容的主控SDK都不存在需要重复初始化和关闭Wire的情况，所以没有添加这两行。因为这同样也会一定程度降低通信效率。
![image](https://github.com/DFRobot/DFRobot_INA219/assets/78136558/72d50b9d-574a-462b-8606-6c48450fd7d9)

**Comment by pleasetakeup** [comment]
very good
